#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  exampleSheet.py
#  
#  Copyright 2015 Romadmin <rdelro@users.noreply.github.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  original code http://code.activestate.com/recipes/579064-hex-dump/?in=lang-python credits!



def group(a, *ns):
	for n in ns:
		a = [a[i:i+n] for i in xrange(0, len(a), n)]
	return a
def join(a, *cs):
	return [cs[0].join(join(t, *cs[1:])) for t in a] if cs else a

def hexdump(data):
	toHex = lambda c: '{:02X}'.format(ord(c))
	toChr = lambda c: c if 32 <=ord(c) < 127 else '.'
	make = lambda f, *cs: join(group(map(f, data), 8, 2), *cs)
	hs = make (toHex, ' ', ' ')
	cs = make(toChr, ' ', ' ')
	for i, (h, c) in enumerate(zip(hs, cs)):
		print '{:010X}: {:48}  {:16}'.format(i * 16, h, c)
